### PR TITLE
Added snapcraft.yaml file for creating snap.

### PR DESCRIPTION
**Pull request by letozaf**
Hello I am Carla, I am part of the Ubuntu Community. I have created a snapcraft.yaml file so kurly can be installed as a snap on Ubuntu and the other Linux distributions that support snaps.
You can test the snapcraft.yaml file by running ```snapcraft`` in the root of the project.

### CODE REVIEW

**Comment by davidjpeacock** [comment]
Hey Carla,

Thank you for the PR!

Snaps are new to me; I'm familiar with the traditional apt package system; can you elaborate a little on this environment?  Is this controlled by / audited by Ubuntu or are these outside of the Canonical setup?

Very much appreciated.

David

**Comment by letozaf** [comment]
Hey David,

You're Welcome :D.
Snaps are used/supported by many Linux distributions, there is a lot about them here:

https://snapcraft.io/

The nice thing about Snaps is that it's a zip file containing an application together with its dependencies, this means you can install them on almost any Linux distribution and version as you do not have to worry about dependencies.

Hope you get all the answers to you questions from the website above, otherwise do not hesitate to ask me :), hope I can answer :).

Carla

**Comment by davidjpeacock** [comment]
Thank you; I'll play with this when I get some time and see how it all fits together.

Again, very much appreciate the PR.

**Comment by letozaf** [comment]
Hello David,
I made a blog post on how to package a Go snap and I used Kurly as and example, you can read it here:
https://carla-sella.blogspot.com/2017/07/packaging-up-go-app-as-snap-after.html
This can help you figure out how Snapcraft and Snaps work.
Bye.
Carla

**Comment by davidjpeacock** [comment]
Sorry for the delay Carla, I just got to trying this out and hit a roadblock very early on with my environment.  Apparently snapcraft isn't easy to find for my Fedora system.

I'll sort out issues my end then test ASAP.

Thank you for your patience, and again, my apologies.

**Comment by davidjpeacock** [comment]
Hi @letozaf!

I've setup an Ubuntu 16.04 environment and have attempted to run snapcraft, but it looks like I'm erroring somewhere.

Is there a specific reason you used Go 1.6?  I'm wondering if latest stable would be better?

Please advise when you get a chance.

Thank you!
David

```shell
$ snapcraft 
"grade" property not specified: defaulting to "stable"
Installing build dependencies: golang-1.6-go golang-1.6-race-detector-runtime golang-1.6-src golang-go golang-race-detector-runtime golang-src
[sudo] password for peacock: 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Suggested packages:
  bzr mercurial subversion
The following NEW packages will be installed:
  golang-1.6-go golang-1.6-race-detector-runtime golang-1.6-src golang-go golang-race-detector-runtime golang-src
0 upgraded, 6 newly installed, 0 to remove and 0 not upgraded.
Need to get 27.0 MB of archives.
After this operation, 198 MB of additional disk space will be used.
Get:1 http://ca.archive.ubuntu.com/ubuntu xenial-updates/main amd64 golang-1.6-src amd64 1.6.2-0ubuntu5~16.04.3 [6,415 kB]
Get:2 http://ca.archive.ubuntu.com/ubuntu xenial-updates/main amd64 golang-1.6-go amd64 1.6.2-0ubuntu5~16.04.3 [20.2 MB]
Get:3 http://ca.archive.ubuntu.com/ubuntu xenial/main amd64 golang-src amd64 2:1.6-1ubuntu4 [3,066 B]                                                                                                             
Get:4 http://ca.archive.ubuntu.com/ubuntu xenial/main amd64 golang-go amd64 2:1.6-1ubuntu4 [21.8 kB]                                                                                                              
Get:5 http://ca.archive.ubuntu.com/ubuntu xenial/main amd64 golang-1.6-race-detector-runtime amd64 0.0+svn252922-0ubuntu1 [404 kB]                                                                                
Get:6 http://ca.archive.ubuntu.com/ubuntu xenial/main amd64 golang-race-detector-runtime amd64 2:1.6-1ubuntu4 [2,854 B]                                                                                           
Fetched 27.0 MB in 29s (908 kB/s)                                                                                                                                                                                 
Selecting previously unselected package golang-1.6-src.
(Reading database ... 217790 files and directories currently installed.)
Preparing to unpack .../golang-1.6-src_1.6.2-0ubuntu5~16.04.3_amd64.deb ...
Unpacking golang-1.6-src (1.6.2-0ubuntu5~16.04.3) ...
Selecting previously unselected package golang-1.6-go.
Preparing to unpack .../golang-1.6-go_1.6.2-0ubuntu5~16.04.3_amd64.deb ...
Unpacking golang-1.6-go (1.6.2-0ubuntu5~16.04.3) ...
Selecting previously unselected package golang-src.
Preparing to unpack .../golang-src_2%3a1.6-1ubuntu4_amd64.deb ...
Unpacking golang-src (2:1.6-1ubuntu4) ...
Selecting previously unselected package golang-go.
Preparing to unpack .../golang-go_2%3a1.6-1ubuntu4_amd64.deb ...
Unpacking golang-go (2:1.6-1ubuntu4) ...
Selecting previously unselected package golang-1.6-race-detector-runtime.
Preparing to unpack .../golang-1.6-race-detector-runtime_0.0+svn252922-0ubuntu1_amd64.deb ...
Unpacking golang-1.6-race-detector-runtime (0.0+svn252922-0ubuntu1) ...
Selecting previously unselected package golang-race-detector-runtime.
Preparing to unpack .../golang-race-detector-runtime_2%3a1.6-1ubuntu4_amd64.deb ...
Unpacking golang-race-detector-runtime (2:1.6-1ubuntu4) ...
Processing triggers for man-db (2.7.5-1) ...
Setting up golang-1.6-src (1.6.2-0ubuntu5~16.04.3) ...
Setting up golang-1.6-go (1.6.2-0ubuntu5~16.04.3) ...
Setting up golang-src (2:1.6-1ubuntu4) ...
Setting up golang-go (2:1.6-1ubuntu4) ...
Setting up golang-1.6-race-detector-runtime (0.0+svn252922-0ubuntu1) ...
Setting up golang-race-detector-runtime (2:1.6-1ubuntu4) ...
golang-1.6-go set to automatically installed.
golang-1.6-race-detector-runtime set to automatically installed.
golang-1.6-src set to automatically installed.
golang-go set to automatically installed.
golang-race-detector-runtime set to automatically installed.
golang-src set to automatically installed.
Preparing to pull kurly 
Pulling kurly 
go get -t -d ./github.com/davidjpeacock/kurly/...
Preparing to build kurly 
Building kurly 
go build -o /home/peacock/.ssh/kurly/parts/kurly/go/bin/kurly github.com/davidjpeacock/kurly
# github.com/davidjpeacock/kurly
github.com/davidjpeacock/kurly/options.go:141: undefined: http.ErrUseLastResponse
Command '['/bin/sh', '/tmp/tmp0px74fdg', 'go', 'build', '-o', '/home/peacock/.ssh/kurly/parts/kurly/go/bin/kurly', 'github.com/davidjpeacock/kurly']' returned non-zero exit status 2
```

**Comment by letozaf** [comment]
Hi David,
Sorry for not answering yesterday, but I was away.
Yes I think you need a more recent version of go. This evening I will install Ubuntu 16.04 on a Virtual Machine and test a new yaml file modified so to use another version of go and then update my PR.

**Comment by davidjpeacock** [comment]
Hey Carla,

No apologies necessary. :-)

Cool cool - I'll wait for your next commit.

Thank you!

David

**Comment by letozaf** [comment]
For Fedora there is a snapcore/snapcraft docker image and the Ubuntu developers are telling me that they are working on making snapcraft usable in Fedora.

https://hub.docker.com/r/snapcore/snapcraft/

**Comment by davidjpeacock** [comment]
Worked like a charm. :-)  Thank you!

:+1:

**Comment by letozaf** [comment]
You're Welcome :D.
I can suggest you to use build.snapcraft.io (https://build.snapcraft.io/)  to automate the delivery with a few clicks.

**Comment by davidjpeacock** [comment]
Hey Carla,

Are you happy to volunteer to be the maintainer of the snap?

D

**Pull request merged**
