### PR TITLE
Implement --head AKA -I

### PR DESCRIPTION
**Pull request by davidjpeacock**
Addresses #42; thank you @chr4!

### CODE REVIEW

**Comment by chr4** [comment]
Wow, that was quick! Awesome :) Looking forward to the merge.

**Comment by davidjpeacock** [comment]
Can't make this a success without feedback from people like you @chr4; thank you! :-)

If you're able to build this from source then you can do so after it's merged, otherwise I'll likely bundle up a few more features before the next release.  Happy to do a special build for you too.  Let me know.

Cheers,
David

**Comment by chr4** [comment]
Thanks! I'm building from source, so once this is merged, I'll give it a shot.

**Comment by davidjpeacock** [comment]
@chr4 Sorry for the bad news but actually my implementation here wasn't a good one.  I'm going to retract this PR and work on a new one.  I'll reopen #42 in the meanwhile.  :-)  My apologies.

**Pull request closed without merging**
